language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - cd src
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

before_install:
  - cd src

install: travis_retry composer install --no-interaction --prefer-source

script: src/vendor/bin/phpunit --verbose